version: '1'
name: backend
services:
    cobra-viper-demo:
        container_name: cobra-viper-demo
        build: .
        ports:
            - "8085:8080"
        environment:
            - dfogg_database_mysql=${dfogg_database_mysql}