name: backend-deployment
on: push

jobs:
  ci_lint:
    name: ci_lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.1

  deploy_to_railway:
    name: deploy_to_railway
    runs-on: ubuntu-latest
    needs: ci_lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: install packages
        run: go mod download && go mod verify

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service cobra-demo
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}